### PR TITLE
Bug 1210533 - update marionette (client, driver), submodule update

### PR DESCRIPTION
**Pull request by mjzffr**
```
marionette-client == 2.0.0
marionette-driver == 1.1.1
```

This is not ready to be merged. I will update the submodule once Bug 1223543 is resolved.

### CODE REVIEW

**Comment by sydvicious** [comment]
This looks straightforward. Once all of other pieces are ready, this can be merged.

**Comment by mjzffr** [comment]
I'm testing on pf-jenkins using the `pf-jenkins-new_runner` branch. No harness failures so far:
- bw-limits eme: http://pf-jenkins.qa.mtv2.mozilla.com:8080/job/temp_mn-eme-bw-limits-netflix-default-nightly-win_32_64/1/console
- mse yt default: http://pf-jenkins.qa.mtv2.mozilla.com:8080/job/temp_test-mn-mse-youtube-default-nightly-win7_32_64/73/console
- mse default: http://pf-jenkins.qa.mtv2.mozilla.com:8080/job/temp_test-mn-mse-youtube-basic-y-nightly-mac/69/console
- bw-limits mse: http://pf-jenkins.qa.mtv2.mozilla.com:8080/job/temp_mn-mse-bw-limits-youtube-default-nightly-mac/1/console

Test failure recorded correctly on Treeherder: https://treeherder.allizom.org/logviewer.html#?job_id=2340786&repo=mozilla-central

So I think we're good to go. @sydvicious this is now ready for final review.

**Comment by sydvicious** [comment]
r+. Looks good.

**Comment by mjzffr** [comment]
Merged into master as b8e937f7

**Pull request closed without merging**
